---
- fail:
    msg: You may only define one of 'cryptdisks_mount.uuid' or 'cryptdisks_mount.net_path'
  when: cryptdisks_mount.uuid is defined and cryptdisks_mount.net_path is defined

- name: Create folder for the cryptdisks mount point
  become: true
  file:
    state: directory
    owner: root
    group: root
    mode: '0700'
    path: "{{ cryptdisks_mount.mount_point }}"

- name: "Configure `CRYPTDISKS_MOUNT` in '{{ cryptdisks_path }}'"
  become: true
  lineinfile:
    path: "{{ cryptdisks_path }}"
    regexp: '^CRYPTDISKS_MOUNT=.+'
    line: "CRYPTDISKS_MOUNT=\"{{ cryptdisks_mount.mount_point | default('') }}\""

- name: Push out the credentials file
  become: true
  template:
    src: smbcredentials.j2
    dest: "{{ cryptdisks_mount.net_credentials.path }}"
    owner: root
    group: root
    mode: '0600'
  when: cryptdisks_mount.net_credentials.path is defined
